# Generated by Django 5.1.3 on 2024-11-21 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comentarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coments",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
